language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script: "coverage run -m crawler.tests"
after_success:
  - coveralls
